version: '3.5'
services:
    database:
        image: mongo:latest
        ports:
        - 27001:27017
    backend:
        build: ./backend
        ports:
            - 1245:1245
        depends_on:
            - database
    # frontend:
    #     build: ./frontend
    #     ports: 
    #         - 9001:80